/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -a qatemconnection_adaptor.h: com.blackmagicdesign.QAtemConnection.xml
 *
 * qdbusxml2cpp is Copyright (C) 2012 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef QATEMCONNECTION_ADAPTOR_H_1415248144
#define QATEMCONNECTION_ADAPTOR_H_1415248144

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface com.blackmagicdesign.QAtemConnection
 */
class QAtemConnectionAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.blackmagicdesign.QAtemConnection")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.blackmagicdesign.QAtemConnection\">\n"
"    <signal name=\"connected\"/>\n"
"    <signal name=\"disconnected\"/>\n"
"    <signal name=\"socketError\">\n"
"      <arg direction=\"out\" type=\"s\" name=\"errorString\"/>\n"
"    </signal>\n"
"    <signal name=\"programInputChanged\">\n"
"      <arg direction=\"out\" type=\"q\" name=\"oldIndex\"/>\n"
"      <arg direction=\"out\" type=\"q\" name=\"newIndex\"/>\n"
"    </signal>\n"
"    <signal name=\"previewInputChanged\">\n"
"      <arg direction=\"out\" type=\"q\" name=\"oldIndex\"/>\n"
"      <arg direction=\"out\" type=\"q\" name=\"newIndex\"/>\n"
"    </signal>\n"
"    <signal name=\"tallyStatesChanged\"/>\n"
"    <signal name=\"transitionPreviewChanged\">\n"
"      <arg direction=\"out\" type=\"b\" name=\"state\"/>\n"
"    </signal>\n"
"    <signal name=\"transitionFrameCountChanged\">\n"
"      <arg direction=\"out\" type=\"y\" name=\"count\"/>\n"
"    </signal>\n"
"    <signal name=\"transitionPositionChanged\">\n"
"      <arg direction=\"out\" type=\"q\" name=\"count\"/>\n"
"    </signal>\n"
"    <signal name=\"nextTransitionStyleChanged\">\n"
"      <arg direction=\"out\" type=\"y\" name=\"style\"/>\n"
"    </signal>\n"
"    <signal name=\"keyersOnNextTransitionChanged\">\n"
"      <arg direction=\"out\" type=\"y\" name=\"keyers\"/>\n"
"    </signal>\n"
"    <signal name=\"currentTransitionStyleChanged\">\n"
"      <arg direction=\"out\" type=\"y\" name=\"style\"/>\n"
"    </signal>\n"
"    <signal name=\"keyersOnCurrentTransitionChanged\">\n"
"      <arg direction=\"out\" type=\"y\" name=\"keyers\"/>\n"
"    </signal>\n"
"    <signal name=\"fadeToBlackChanged\">\n"
"      <arg direction=\"out\" type=\"b\" name=\"fading\"/>\n"
"      <arg direction=\"out\" type=\"b\" name=\"enabled\"/>\n"
"    </signal>\n"
"    <signal name=\"fadeToBlackFrameCountChanged\">\n"
"      <arg direction=\"out\" type=\"y\" name=\"count\"/>\n"
"    </signal>\n"
"    <signal name=\"fadeToBlackFramesChanged\">\n"
"      <arg direction=\"out\" type=\"y\" name=\"frames\"/>\n"
"    </signal>\n"
"    <signal name=\"downstreamKeyOnChanged\">\n"
"      <arg direction=\"out\" type=\"y\" name=\"keyer\"/>\n"
"      <arg direction=\"out\" type=\"b\" name=\"state\"/>\n"
"    </signal>\n"
"    <signal name=\"downstreamKeyTieChanged\">\n"
"      <arg direction=\"out\" type=\"y\" name=\"keyer\"/>\n"
"      <arg direction=\"out\" type=\"b\" name=\"state\"/>\n"
"    </signal>\n"
"    <signal name=\"downstreamKeyFrameCountChanged\">\n"
"      <arg direction=\"out\" type=\"y\" name=\"keyer\"/>\n"
"      <arg direction=\"out\" type=\"y\" name=\"count\"/>\n"
"    </signal>\n"
"    <signal name=\"downstreamKeyFramesChanged\">\n"
"      <arg direction=\"out\" type=\"y\" name=\"keyer\"/>\n"
"      <arg direction=\"out\" type=\"y\" name=\"frames\"/>\n"
"    </signal>\n"
"    <signal name=\"downstreamKeySourcesChanged\">\n"
"      <arg direction=\"out\" type=\"y\" name=\"keyer\"/>\n"
"      <arg direction=\"out\" type=\"q\" name=\"fill\"/>\n"
"      <arg direction=\"out\" type=\"q\" name=\"key\"/>\n"
"    </signal>\n"
"    <signal name=\"downstreamKeyInvertKeyChanged\">\n"
"      <arg direction=\"out\" type=\"y\" name=\"keyer\"/>\n"
"      <arg direction=\"out\" type=\"b\" name=\"invert\"/>\n"
"    </signal>\n"
"    <signal name=\"downstreamKeyPreMultipliedChanged\">\n"
"      <arg direction=\"out\" type=\"y\" name=\"keyer\"/>\n"
"      <arg direction=\"out\" type=\"b\" name=\"preMultiplied\"/>\n"
"    </signal>\n"
"    <signal name=\"downstreamKeyEnableMaskChanged\">\n"
"      <arg direction=\"out\" type=\"y\" name=\"keyer\"/>\n"
"      <arg direction=\"out\" type=\"b\" name=\"enable\"/>\n"
"    </signal>\n"
"    <signal name=\"upstreamKeyOnChanged\">\n"
"      <arg direction=\"out\" type=\"y\" name=\"keyer\"/>\n"
"      <arg direction=\"out\" type=\"b\" name=\"state\"/>\n"
"    </signal>\n"
"    <signal name=\"upstreamKeyTypeChanged\">\n"
"      <arg direction=\"out\" type=\"y\" name=\"keyer\"/>\n"
"      <arg direction=\"out\" type=\"y\" name=\"type\"/>\n"
"    </signal>\n"
"    <signal name=\"upstreamKeyFillSourceChanged\">\n"
"      <arg direction=\"out\" type=\"y\" name=\"keyer\"/>\n"
"      <arg direction=\"out\" type=\"q\" name=\"source\"/>\n"
"    </signal>\n"
"    <signal name=\"upstreamKeyKeySourceChanged\">\n"
"      <arg direction=\"out\" type=\"y\" name=\"keyer\"/>\n"
"      <arg direction=\"out\" type=\"q\" name=\"source\"/>\n"
"    </signal>\n"
"    <signal name=\"upstreamKeyEnableMaskChanged\">\n"
"      <arg direction=\"out\" type=\"y\" name=\"keyer\"/>\n"
"      <arg direction=\"out\" type=\"b\" name=\"enable\"/>\n"
"    </signal>\n"
"    <signal name=\"upstreamKeyLumaPreMultipliedKeyChanged\">\n"
"      <arg direction=\"out\" type=\"y\" name=\"keyer\"/>\n"
"      <arg direction=\"out\" type=\"b\" name=\"preMultiplied\"/>\n"
"    </signal>\n"
"    <signal name=\"upstreamKeyLumaInvertKeyChanged\">\n"
"      <arg direction=\"out\" type=\"y\" name=\"keyer\"/>\n"
"      <arg direction=\"out\" type=\"b\" name=\"invert\"/>\n"
"    </signal>\n"
"    <signal name=\"upstreamKeyChromaNarrowRangeChanged\">\n"
"      <arg direction=\"out\" type=\"y\" name=\"keyer\"/>\n"
"      <arg direction=\"out\" type=\"b\" name=\"narrowRange\"/>\n"
"    </signal>\n"
"    <signal name=\"upstreamKeyPatternPatternChanged\">\n"
"      <arg direction=\"out\" type=\"y\" name=\"keyer\"/>\n"
"      <arg direction=\"out\" type=\"y\" name=\"pattern\"/>\n"
"    </signal>\n"
"    <signal name=\"upstreamKeyPatternInvertPatternChanged\">\n"
"      <arg direction=\"out\" type=\"y\" name=\"keyer\"/>\n"
"      <arg direction=\"out\" type=\"b\" name=\"invert\"/>\n"
"    </signal>\n"
"    <signal name=\"upstreamKeyDVEEnableDropShadowChanged\">\n"
"      <arg direction=\"out\" type=\"y\" name=\"keyer\"/>\n"
"      <arg direction=\"out\" type=\"b\" name=\"enable\"/>\n"
"    </signal>\n"
"    <signal name=\"upstreamKeyDVELightSourceAltitudeChanged\">\n"
"      <arg direction=\"out\" type=\"y\" name=\"keyer\"/>\n"
"      <arg direction=\"out\" type=\"y\" name=\"altitude\"/>\n"
"    </signal>\n"
"    <signal name=\"upstreamKeyDVEEnableBorderChanged\">\n"
"      <arg direction=\"out\" type=\"y\" name=\"keyer\"/>\n"
"      <arg direction=\"out\" type=\"b\" name=\"enable\"/>\n"
"    </signal>\n"
"    <signal name=\"upstreamKeyDVEBorderStyleChanged\">\n"
"      <arg direction=\"out\" type=\"y\" name=\"keyer\"/>\n"
"      <arg direction=\"out\" type=\"y\" name=\"style\"/>\n"
"    </signal>\n"
"    <signal name=\"upstreamKeyDVEBorderOutsideSoftenChanged\">\n"
"      <arg direction=\"out\" type=\"y\" name=\"keyer\"/>\n"
"      <arg direction=\"out\" type=\"y\" name=\"soften\"/>\n"
"    </signal>\n"
"    <signal name=\"upstreamKeyDVEBorderInsideSoftenChanged\">\n"
"      <arg direction=\"out\" type=\"y\" name=\"keyer\"/>\n"
"      <arg direction=\"out\" type=\"y\" name=\"soften\"/>\n"
"    </signal>\n"
"    <signal name=\"upstreamKeyDVEBorderOpacityChanged\">\n"
"      <arg direction=\"out\" type=\"y\" name=\"keyer\"/>\n"
"      <arg direction=\"out\" type=\"y\" name=\"opacity\"/>\n"
"    </signal>\n"
"    <signal name=\"upstreamKeyDVERateChanged\">\n"
"      <arg direction=\"out\" type=\"y\" name=\"keyer\"/>\n"
"      <arg direction=\"out\" type=\"y\" name=\"rate\"/>\n"
"    </signal>\n"
"    <signal name=\"upstreamKeyDVEKeyFrameASetChanged\">\n"
"      <arg direction=\"out\" type=\"y\" name=\"keyer\"/>\n"
"      <arg direction=\"out\" type=\"b\" name=\"set\"/>\n"
"    </signal>\n"
"    <signal name=\"upstreamKeyDVEKeyFrameBSetChanged\">\n"
"      <arg direction=\"out\" type=\"y\" name=\"keyer\"/>\n"
"      <arg direction=\"out\" type=\"b\" name=\"set\"/>\n"
"    </signal>\n"
"    <signal name=\"upstreamKeyEnableFlyChanged\">\n"
"      <arg direction=\"out\" type=\"y\" name=\"keyer\"/>\n"
"      <arg direction=\"out\" type=\"b\" name=\"enabled\"/>\n"
"    </signal>\n"
"    <signal name=\"mediaPlayerChanged\">\n"
"      <arg direction=\"out\" type=\"y\" name=\"player\"/>\n"
"      <arg direction=\"out\" type=\"y\" name=\"type\"/>\n"
"      <arg direction=\"out\" type=\"y\" name=\"still\"/>\n"
"      <arg direction=\"out\" type=\"y\" name=\"clip\"/>\n"
"    </signal>\n"
"    <signal name=\"auxSourceChanged\">\n"
"      <arg direction=\"out\" type=\"y\" name=\"aux\"/>\n"
"      <arg direction=\"out\" type=\"q\" name=\"source\"/>\n"
"    </signal>\n"
"    <signal name=\"productInformationChanged\">\n"
"      <arg direction=\"out\" type=\"s\" name=\"info\"/>\n"
"    </signal>\n"
"    <signal name=\"versionChanged\">\n"
"      <arg direction=\"out\" type=\"q\" name=\"major\"/>\n"
"      <arg direction=\"out\" type=\"q\" name=\"minor\"/>\n"
"    </signal>\n"
"    <signal name=\"timeChanged\">\n"
"      <arg direction=\"out\" type=\"u\" name=\"time\"/>\n"
"    </signal>\n"
"    <signal name=\"mixFramesChanged\">\n"
"      <arg direction=\"out\" type=\"y\" name=\"frames\"/>\n"
"    </signal>\n"
"    <signal name=\"dipFramesChanged\">\n"
"      <arg direction=\"out\" type=\"y\" name=\"frames\"/>\n"
"    </signal>\n"
"    <signal name=\"dipSourceChanged\">\n"
"      <arg direction=\"out\" type=\"q\" name=\"source\"/>\n"
"    </signal>\n"
"    <signal name=\"wipeFramesChanged\">\n"
"      <arg direction=\"out\" type=\"y\" name=\"frames\"/>\n"
"    </signal>\n"
"    <signal name=\"wipeBorderWidthChanged\">\n"
"      <arg direction=\"out\" type=\"q\" name=\"width\"/>\n"
"    </signal>\n"
"    <signal name=\"wipeBorderSoftnessChanged\">\n"
"      <arg direction=\"out\" type=\"q\" name=\"softness\"/>\n"
"    </signal>\n"
"    <signal name=\"wipeTypeChanged\">\n"
"      <arg direction=\"out\" type=\"y\" name=\"type\"/>\n"
"    </signal>\n"
"    <signal name=\"wipeSymmetryChanged\">\n"
"      <arg direction=\"out\" type=\"q\" name=\"value\"/>\n"
"    </signal>\n"
"    <signal name=\"wipeXPositionChanged\">\n"
"      <arg direction=\"out\" type=\"q\" name=\"value\"/>\n"
"    </signal>\n"
"    <signal name=\"wipeYPositionChanged\">\n"
"      <arg direction=\"out\" type=\"q\" name=\"value\"/>\n"
"    </signal>\n"
"    <signal name=\"wipeReverseDirectionChanged\">\n"
"      <arg direction=\"out\" type=\"b\" name=\"reverse\"/>\n"
"    </signal>\n"
"    <signal name=\"wipeFlipFlopChanged\">\n"
"      <arg direction=\"out\" type=\"b\" name=\"flipFlop\"/>\n"
"    </signal>\n"
"    <signal name=\"dveRateChanged\">\n"
"      <arg direction=\"out\" type=\"q\" name=\"frames\"/>\n"
"    </signal>\n"
"    <signal name=\"dveEffectChanged\">\n"
"      <arg direction=\"out\" type=\"y\" name=\"effect\"/>\n"
"    </signal>\n"
"    <signal name=\"dveFillSourceChanged\">\n"
"      <arg direction=\"out\" type=\"q\" name=\"source\"/>\n"
"    </signal>\n"
"    <signal name=\"dveKeySourceChanged\">\n"
"      <arg direction=\"out\" type=\"q\" name=\"source\"/>\n"
"    </signal>\n"
"    <signal name=\"dveEnableKeyChanged\">\n"
"      <arg direction=\"out\" type=\"b\" name=\"enabled\"/>\n"
"    </signal>\n"
"    <signal name=\"dveEnablePreMultipliedKeyChanged\">\n"
"      <arg direction=\"out\" type=\"b\" name=\"enabled\"/>\n"
"    </signal>\n"
"    <signal name=\"dveEnableInvertKeyChanged\">\n"
"      <arg direction=\"out\" type=\"b\" name=\"enabled\"/>\n"
"    </signal>\n"
"    <signal name=\"dveReverseDirectionChanged\">\n"
"      <arg direction=\"out\" type=\"b\" name=\"reverse\"/>\n"
"    </signal>\n"
"    <signal name=\"dveFlipFlopDirectionChanged\">\n"
"      <arg direction=\"out\" type=\"b\" name=\"flipFlop\"/>\n"
"    </signal>\n"
"    <signal name=\"stingerSourceChanged\">\n"
"      <arg direction=\"out\" type=\"y\" name=\"source\"/>\n"
"    </signal>\n"
"    <signal name=\"stingerEnablePreMultipliedKeyChanged\">\n"
"      <arg direction=\"out\" type=\"b\" name=\"enabled\"/>\n"
"    </signal>\n"
"    <signal name=\"stingerEnableInvertKeyChanged\">\n"
"      <arg direction=\"out\" type=\"b\" name=\"enabled\"/>\n"
"    </signal>\n"
"    <signal name=\"stingerPreRollChanged\">\n"
"      <arg direction=\"out\" type=\"q\" name=\"frames\"/>\n"
"    </signal>\n"
"    <signal name=\"stingerClipDurationChanged\">\n"
"      <arg direction=\"out\" type=\"q\" name=\"frames\"/>\n"
"    </signal>\n"
"    <signal name=\"stingerTriggerPointChanged\">\n"
"      <arg direction=\"out\" type=\"q\" name=\"frames\"/>\n"
"    </signal>\n"
"    <signal name=\"stingerMixRateChanged\">\n"
"      <arg direction=\"out\" type=\"q\" name=\"frames\"/>\n"
"    </signal>\n"
"    <signal name=\"wipeBorderSourceChanged\">\n"
"      <arg direction=\"out\" type=\"q\" name=\"index\"/>\n"
"    </signal>\n"
"    <signal name=\"videoFormatChanged\">\n"
"      <arg direction=\"out\" type=\"y\" name=\"format\"/>\n"
"    </signal>\n"
"    <signal name=\"videoDownConvertTypeChanged\">\n"
"      <arg direction=\"out\" type=\"y\" name=\"type\"/>\n"
"    </signal>\n"
"    <signal name=\"mediaPoolClip1SizeChanged\">\n"
"      <arg direction=\"out\" type=\"y\" name=\"size\"/>\n"
"    </signal>\n"
"    <signal name=\"mediaPoolClip2SizeChanged\">\n"
"      <arg direction=\"out\" type=\"y\" name=\"size\"/>\n"
"    </signal>\n"
"    <signal name=\"audioMonitorEnabledChanged\">\n"
"      <arg direction=\"out\" type=\"b\" name=\"enabled\"/>\n"
"    </signal>\n"
"    <signal name=\"audioMonitorMutedChanged\">\n"
"      <arg direction=\"out\" type=\"b\" name=\"muted\"/>\n"
"    </signal>\n"
"    <signal name=\"audioMonitorDimmedChanged\">\n"
"      <arg direction=\"out\" type=\"b\" name=\"dimmed\"/>\n"
"    </signal>\n"
"    <signal name=\"audioLevelsChanged\"/>\n"
"    <signal name=\"mediaLockStateChanged\">\n"
"      <arg direction=\"out\" type=\"y\" name=\"id\"/>\n"
"      <arg direction=\"out\" type=\"b\" name=\"state\"/>\n"
"    </signal>\n"
"    <signal name=\"dataTransferFinished\">\n"
"      <arg direction=\"out\" type=\"q\" name=\"transferId\"/>\n"
"    </signal>\n"
"    <method name=\"connectToSwitcher\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"name\"/>\n"
"    </method>\n"
"    <method name=\"disconnectFromSwitcher\"/>\n"
"    <method name=\"setDebugEnabled\">\n"
"      <arg direction=\"in\" type=\"b\" name=\"enabled\"/>\n"
"    </method>\n"
"    <method name=\"debugEnabled\">\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"    </method>\n"
"    <method name=\"programInput\">\n"
"      <arg direction=\"out\" type=\"q\"/>\n"
"    </method>\n"
"    <method name=\"previewInput\">\n"
"      <arg direction=\"out\" type=\"q\"/>\n"
"    </method>\n"
"    <method name=\"tallyState\">\n"
"      <arg direction=\"out\" type=\"y\"/>\n"
"      <arg direction=\"in\" type=\"y\" name=\"id\"/>\n"
"    </method>\n"
"    <method name=\"tallyStateCount\">\n"
"      <arg direction=\"out\" type=\"y\"/>\n"
"    </method>\n"
"    <method name=\"transitionPreviewEnabled\">\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"    </method>\n"
"    <method name=\"transitionFrameCount\">\n"
"      <arg direction=\"out\" type=\"y\"/>\n"
"    </method>\n"
"    <method name=\"transitionPosition\">\n"
"      <arg direction=\"out\" type=\"q\"/>\n"
"    </method>\n"
"    <method name=\"keyersOnNextTransition\">\n"
"      <arg direction=\"out\" type=\"y\"/>\n"
"    </method>\n"
"    <method name=\"nextTransitionStyle\">\n"
"      <arg direction=\"out\" type=\"y\"/>\n"
"    </method>\n"
"    <method name=\"keyersOnCurrentTransition\">\n"
"      <arg direction=\"out\" type=\"y\"/>\n"
"    </method>\n"
"    <method name=\"currentTransitionStyle\">\n"
"      <arg direction=\"out\" type=\"y\"/>\n"
"    </method>\n"
"    <method name=\"fadeToBlackEnabled\">\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"    </method>\n"
"    <method name=\"fadeToBlackFading\">\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"    </method>\n"
"    <method name=\"fadeToBlackFrameCount\">\n"
"      <arg direction=\"out\" type=\"y\"/>\n"
"    </method>\n"
"    <method name=\"fadeToBlackFrames\">\n"
"      <arg direction=\"out\" type=\"y\"/>\n"
"    </method>\n"
"    <method name=\"downstreamKeyOn\">\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"      <arg direction=\"in\" type=\"y\" name=\"keyer\"/>\n"
"    </method>\n"
"    <method name=\"downstreamKeyTie\">\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"      <arg direction=\"in\" type=\"y\" name=\"keyer\"/>\n"
"    </method>\n"
"    <method name=\"downstreamKeyFrameCount\">\n"
"      <arg direction=\"out\" type=\"y\"/>\n"
"      <arg direction=\"in\" type=\"y\" name=\"keyer\"/>\n"
"    </method>\n"
"    <method name=\"downstreamKeyFrames\">\n"
"      <arg direction=\"out\" type=\"y\"/>\n"
"      <arg direction=\"in\" type=\"y\" name=\"keyer\"/>\n"
"    </method>\n"
"    <method name=\"downstreamKeyFillSource\">\n"
"      <arg direction=\"out\" type=\"q\"/>\n"
"      <arg direction=\"in\" type=\"y\" name=\"keyer\"/>\n"
"    </method>\n"
"    <method name=\"downstreamKeyKeySource\">\n"
"      <arg direction=\"out\" type=\"q\"/>\n"
"      <arg direction=\"in\" type=\"y\" name=\"keyer\"/>\n"
"    </method>\n"
"    <method name=\"downstreamKeyInvertKey\">\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"      <arg direction=\"in\" type=\"y\" name=\"keyer\"/>\n"
"    </method>\n"
"    <method name=\"downstreamKeyPreMultiplied\">\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"      <arg direction=\"in\" type=\"y\" name=\"keyer\"/>\n"
"    </method>\n"
"    <method name=\"downstreamKeyClip\">\n"
"      <arg direction=\"out\" type=\"q\"/>\n"
"      <arg direction=\"in\" type=\"y\" name=\"keyer\"/>\n"
"    </method>\n"
"    <method name=\"downstreamKeyGain\">\n"
"      <arg direction=\"out\" type=\"q\"/>\n"
"      <arg direction=\"in\" type=\"y\" name=\"keyer\"/>\n"
"    </method>\n"
"    <method name=\"downstreamKeyEnableMask\">\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"      <arg direction=\"in\" type=\"y\" name=\"keyer\"/>\n"
"    </method>\n"
"    <method name=\"downstreamKeyTopMask\">\n"
"      <arg direction=\"out\" type=\"n\"/>\n"
"      <arg direction=\"in\" type=\"y\" name=\"keyer\"/>\n"
"    </method>\n"
"    <method name=\"downstreamKeyBottomMask\">\n"
"      <arg direction=\"out\" type=\"n\"/>\n"
"      <arg direction=\"in\" type=\"y\" name=\"keyer\"/>\n"
"    </method>\n"
"    <method name=\"downstreamKeyLeftMask\">\n"
"      <arg direction=\"out\" type=\"n\"/>\n"
"      <arg direction=\"in\" type=\"y\" name=\"keyer\"/>\n"
"    </method>\n"
"    <method name=\"downstreamKeyRightMask\">\n"
"      <arg direction=\"out\" type=\"n\"/>\n"
"      <arg direction=\"in\" type=\"y\" name=\"keyer\"/>\n"
"    </method>\n"
"    <method name=\"upstreamKeyOn\">\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"      <arg direction=\"in\" type=\"y\" name=\"keyer\"/>\n"
"    </method>\n"
"    <method name=\"upstreamKeyType\">\n"
"      <arg direction=\"out\" type=\"y\"/>\n"
"      <arg direction=\"in\" type=\"y\" name=\"keyer\"/>\n"
"    </method>\n"
"    <method name=\"upstreamKeyFillSource\">\n"
"      <arg direction=\"out\" type=\"q\"/>\n"
"      <arg direction=\"in\" type=\"y\" name=\"keyer\"/>\n"
"    </method>\n"
"    <method name=\"upstreamKeyKeySource\">\n"
"      <arg direction=\"out\" type=\"q\"/>\n"
"      <arg direction=\"in\" type=\"y\" name=\"keyer\"/>\n"
"    </method>\n"
"    <method name=\"upstreamKeyEnableMask\">\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"      <arg direction=\"in\" type=\"y\" name=\"keyer\"/>\n"
"    </method>\n"
"    <method name=\"upstreamKeyLumaPreMultipliedKey\">\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"      <arg direction=\"in\" type=\"y\" name=\"keyer\"/>\n"
"    </method>\n"
"    <method name=\"upstreamKeyLumaInvertKey\">\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"      <arg direction=\"in\" type=\"y\" name=\"keyer\"/>\n"
"    </method>\n"
"    <method name=\"upstreamKeyChromaNarrowRange\">\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"      <arg direction=\"in\" type=\"y\" name=\"keyer\"/>\n"
"    </method>\n"
"    <method name=\"upstreamKeyPatternPattern\">\n"
"      <arg direction=\"out\" type=\"y\"/>\n"
"      <arg direction=\"in\" type=\"y\" name=\"keyer\"/>\n"
"    </method>\n"
"    <method name=\"upstreamKeyPatternInvertPattern\">\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"      <arg direction=\"in\" type=\"y\" name=\"keyer\"/>\n"
"    </method>\n"
"    <method name=\"upstreamKeyDVEDropShadowEnabled\">\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"      <arg direction=\"in\" type=\"y\" name=\"keyer\"/>\n"
"    </method>\n"
"    <method name=\"upstreamKeyDVELightSourceAltitude\">\n"
"      <arg direction=\"out\" type=\"y\"/>\n"
"      <arg direction=\"in\" type=\"y\" name=\"keyer\"/>\n"
"    </method>\n"
"    <method name=\"upstreamKeyDVEBorderEnabled\">\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"      <arg direction=\"in\" type=\"y\" name=\"keyer\"/>\n"
"    </method>\n"
"    <method name=\"upstreamKeyDVEBorderStyle\">\n"
"      <arg direction=\"out\" type=\"y\"/>\n"
"      <arg direction=\"in\" type=\"y\" name=\"keyer\"/>\n"
"    </method>\n"
"    <method name=\"upstreamKeyDVEBorderOutsideSoften\">\n"
"      <arg direction=\"out\" type=\"y\"/>\n"
"      <arg direction=\"in\" type=\"y\" name=\"keyer\"/>\n"
"    </method>\n"
"    <method name=\"upstreamKeyDVEBorderInsideSoften\">\n"
"      <arg direction=\"out\" type=\"y\"/>\n"
"      <arg direction=\"in\" type=\"y\" name=\"keyer\"/>\n"
"    </method>\n"
"    <method name=\"upstreamKeyDVEBorderOpacity\">\n"
"      <arg direction=\"out\" type=\"y\"/>\n"
"      <arg direction=\"in\" type=\"y\" name=\"keyer\"/>\n"
"    </method>\n"
"    <method name=\"upstreamKeyDVEBorderBevelSofter\">\n"
"      <arg direction=\"out\" type=\"y\"/>\n"
"      <arg direction=\"in\" type=\"y\" name=\"keyer\"/>\n"
"    </method>\n"
"    <method name=\"upstreamKeyDVERate\">\n"
"      <arg direction=\"out\" type=\"y\"/>\n"
"      <arg direction=\"in\" type=\"y\" name=\"keyer\"/>\n"
"    </method>\n"
"    <method name=\"upstreamKeyDVEKeyFrameASet\">\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"      <arg direction=\"in\" type=\"y\" name=\"keyer\"/>\n"
"    </method>\n"
"    <method name=\"upstreamKeyDVEKeyFrameBSet\">\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"      <arg direction=\"in\" type=\"y\" name=\"keyer\"/>\n"
"    </method>\n"
"    <method name=\"upstreamKeyEnableFly\">\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"      <arg direction=\"in\" type=\"y\" name=\"keyer\"/>\n"
"    </method>\n"
"    <method name=\"mediaPlayerType\">\n"
"      <arg direction=\"out\" type=\"y\"/>\n"
"      <arg direction=\"in\" type=\"y\" name=\"player\"/>\n"
"    </method>\n"
"    <method name=\"mediaPlayerSelectedStill\">\n"
"      <arg direction=\"out\" type=\"y\"/>\n"
"      <arg direction=\"in\" type=\"y\" name=\"player\"/>\n"
"    </method>\n"
"    <method name=\"mediaPlayerSelectedClip\">\n"
"      <arg direction=\"out\" type=\"y\"/>\n"
"      <arg direction=\"in\" type=\"y\" name=\"player\"/>\n"
"    </method>\n"
"    <method name=\"auxSource\">\n"
"      <arg direction=\"out\" type=\"q\"/>\n"
"      <arg direction=\"in\" type=\"y\" name=\"aux\"/>\n"
"    </method>\n"
"    <method name=\"productInformation\">\n"
"      <arg direction=\"out\" type=\"s\"/>\n"
"    </method>\n"
"    <method name=\"majorVersion\">\n"
"      <arg direction=\"out\" type=\"q\"/>\n"
"    </method>\n"
"    <method name=\"minorVersion\">\n"
"      <arg direction=\"out\" type=\"q\"/>\n"
"    </method>\n"
"    <method name=\"multiViewLayout\">\n"
"      <arg direction=\"out\" type=\"y\"/>\n"
"    </method>\n"
"    <method name=\"multiViewInput\">\n"
"      <arg direction=\"out\" type=\"y\"/>\n"
"      <arg direction=\"in\" type=\"y\" name=\"multiViewOutput\"/>\n"
"    </method>\n"
"    <method name=\"videoFormat\">\n"
"      <arg direction=\"out\" type=\"y\"/>\n"
"    </method>\n"
"    <method name=\"framesPerSecond\">\n"
"      <arg direction=\"out\" type=\"y\"/>\n"
"    </method>\n"
"    <method name=\"videoDownConvertType\">\n"
"      <arg direction=\"out\" type=\"y\"/>\n"
"    </method>\n"
"    <method name=\"mediaPoolClip1Size\">\n"
"      <arg direction=\"out\" type=\"y\"/>\n"
"    </method>\n"
"    <method name=\"mediaPoolClip2Size\">\n"
"      <arg direction=\"out\" type=\"y\"/>\n"
"    </method>\n"
"    <method name=\"mixFrames\">\n"
"      <arg direction=\"out\" type=\"y\"/>\n"
"    </method>\n"
"    <method name=\"dipFrames\">\n"
"      <arg direction=\"out\" type=\"y\"/>\n"
"    </method>\n"
"    <method name=\"dipSource\">\n"
"      <arg direction=\"out\" type=\"q\"/>\n"
"    </method>\n"
"    <method name=\"wipeFrames\">\n"
"      <arg direction=\"out\" type=\"y\"/>\n"
"    </method>\n"
"    <method name=\"wipeBorderSource\">\n"
"      <arg direction=\"out\" type=\"q\"/>\n"
"    </method>\n"
"    <method name=\"wipeBorderWidth\">\n"
"      <arg direction=\"out\" type=\"q\"/>\n"
"    </method>\n"
"    <method name=\"wipeBorderSoftness\">\n"
"      <arg direction=\"out\" type=\"q\"/>\n"
"    </method>\n"
"    <method name=\"wipeType\">\n"
"      <arg direction=\"out\" type=\"y\"/>\n"
"    </method>\n"
"    <method name=\"wipeSymmetry\">\n"
"      <arg direction=\"out\" type=\"q\"/>\n"
"    </method>\n"
"    <method name=\"wipeXPosition\">\n"
"      <arg direction=\"out\" type=\"q\"/>\n"
"    </method>\n"
"    <method name=\"wipeYPosition\">\n"
"      <arg direction=\"out\" type=\"q\"/>\n"
"    </method>\n"
"    <method name=\"wipeReverseDirection\">\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"    </method>\n"
"    <method name=\"wipeFlipFlop\">\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"    </method>\n"
"    <method name=\"dveRate\">\n"
"      <arg direction=\"out\" type=\"q\"/>\n"
"    </method>\n"
"    <method name=\"dveEffect\">\n"
"      <arg direction=\"out\" type=\"y\"/>\n"
"    </method>\n"
"    <method name=\"dveFillSource\">\n"
"      <arg direction=\"out\" type=\"q\"/>\n"
"    </method>\n"
"    <method name=\"dveKeySource\">\n"
"      <arg direction=\"out\" type=\"q\"/>\n"
"    </method>\n"
"    <method name=\"dveKeyEnabled\">\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"    </method>\n"
"    <method name=\"dvePreMultipliedKeyEnabled\">\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"    </method>\n"
"    <method name=\"dveInvertKeyEnabled\">\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"    </method>\n"
"    <method name=\"dveReverseDirection\">\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"    </method>\n"
"    <method name=\"dveFlipFlopDirection\">\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"    </method>\n"
"    <method name=\"stingerSource\">\n"
"      <arg direction=\"out\" type=\"y\"/>\n"
"    </method>\n"
"    <method name=\"stingerPreMultipliedKeyEnabled\">\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"    </method>\n"
"    <method name=\"stingerInvertKeyEnabled\">\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"    </method>\n"
"    <method name=\"stingerPreRoll\">\n"
"      <arg direction=\"out\" type=\"q\"/>\n"
"    </method>\n"
"    <method name=\"stingerClipDuration\">\n"
"      <arg direction=\"out\" type=\"q\"/>\n"
"    </method>\n"
"    <method name=\"stingerTriggerPoint\">\n"
"      <arg direction=\"out\" type=\"q\"/>\n"
"    </method>\n"
"    <method name=\"stingerMixRate\">\n"
"      <arg direction=\"out\" type=\"q\"/>\n"
"    </method>\n"
"    <method name=\"audioTallyState\">\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"      <arg direction=\"in\" type=\"q\" name=\"index\"/>\n"
"    </method>\n"
"    <method name=\"audioMonitorEnabled\">\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"    </method>\n"
"    <method name=\"audioMonitorMuted\">\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"    </method>\n"
"    <method name=\"audioMonitorDimmed\">\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"    </method>\n"
"    <method name=\"aquireMediaLock\">\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"      <arg direction=\"in\" type=\"y\" name=\"id\"/>\n"
"      <arg direction=\"in\" type=\"y\" name=\"index\"/>\n"
"    </method>\n"
"    <method name=\"unlockMediaLock\">\n"
"      <arg direction=\"in\" type=\"y\" name=\"id\"/>\n"
"    </method>\n"
"    <method name=\"mediaLockState\">\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"      <arg direction=\"in\" type=\"y\" name=\"id\"/>\n"
"    </method>\n"
"    <method name=\"sendDataToSwitcher\">\n"
"      <arg direction=\"out\" type=\"q\"/>\n"
"      <arg direction=\"in\" type=\"y\" name=\"storeId\"/>\n"
"      <arg direction=\"in\" type=\"y\" name=\"index\"/>\n"
"      <arg direction=\"in\" type=\"ay\" name=\"name\"/>\n"
"      <arg direction=\"in\" type=\"ay\" name=\"data\"/>\n"
"    </method>\n"
"    <method name=\"transferActive\">\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"    </method>\n"
"    <method name=\"transferId\">\n"
"      <arg direction=\"out\" type=\"q\"/>\n"
"    </method>\n"
"    <method name=\"remainingTransferDataSize\">\n"
"      <arg direction=\"out\" type=\"i\"/>\n"
"    </method>\n"
"    <method name=\"changeProgramInput\">\n"
"      <arg direction=\"in\" type=\"q\" name=\"index\"/>\n"
"    </method>\n"
"    <method name=\"changePreviewInput\">\n"
"      <arg direction=\"in\" type=\"q\" name=\"index\"/>\n"
"    </method>\n"
"    <method name=\"doCut\"/>\n"
"    <method name=\"doAuto\"/>\n"
"    <method name=\"toggleFadeToBlack\"/>\n"
"    <method name=\"setFadeToBlackFrameRate\">\n"
"      <arg direction=\"in\" type=\"y\" name=\"frames\"/>\n"
"    </method>\n"
"    <method name=\"setTransitionPosition\">\n"
"      <arg direction=\"in\" type=\"q\" name=\"position\"/>\n"
"    </method>\n"
"    <method name=\"signalTransitionPositionChangeDone\"/>\n"
"    <method name=\"setTransitionPreview\">\n"
"      <arg direction=\"in\" type=\"b\" name=\"state\"/>\n"
"    </method>\n"
"    <method name=\"setTransitionType\">\n"
"      <arg direction=\"in\" type=\"y\" name=\"type\"/>\n"
"    </method>\n"
"    <method name=\"setUpstreamKeyOn\">\n"
"      <arg direction=\"in\" type=\"y\" name=\"keyer\"/>\n"
"      <arg direction=\"in\" type=\"b\" name=\"state\"/>\n"
"    </method>\n"
"    <method name=\"setUpstreamKeyOnNextTransition\">\n"
"      <arg direction=\"in\" type=\"y\" name=\"keyer\"/>\n"
"      <arg direction=\"in\" type=\"b\" name=\"state\"/>\n"
"    </method>\n"
"    <method name=\"setBackgroundOnNextTransition\">\n"
"      <arg direction=\"in\" type=\"b\" name=\"state\"/>\n"
"    </method>\n"
"    <method name=\"setUpstreamKeyType\">\n"
"      <arg direction=\"in\" type=\"y\" name=\"keyer\"/>\n"
"      <arg direction=\"in\" type=\"y\" name=\"type\"/>\n"
"    </method>\n"
"    <method name=\"setUpstreamKeyFillSource\">\n"
"      <arg direction=\"in\" type=\"y\" name=\"keyer\"/>\n"
"      <arg direction=\"in\" type=\"q\" name=\"source\"/>\n"
"    </method>\n"
"    <method name=\"setUpstreamKeyKeySource\">\n"
"      <arg direction=\"in\" type=\"y\" name=\"keyer\"/>\n"
"      <arg direction=\"in\" type=\"q\" name=\"source\"/>\n"
"    </method>\n"
"    <method name=\"setUpstreamKeyEnableMask\">\n"
"      <arg direction=\"in\" type=\"y\" name=\"keyer\"/>\n"
"      <arg direction=\"in\" type=\"b\" name=\"enable\"/>\n"
"    </method>\n"
"    <method name=\"setUpstreamKeyLumaPreMultipliedKey\">\n"
"      <arg direction=\"in\" type=\"y\" name=\"keyer\"/>\n"
"      <arg direction=\"in\" type=\"b\" name=\"preMultiplied\"/>\n"
"    </method>\n"
"    <method name=\"setUpstreamKeyLumaInvertKey\">\n"
"      <arg direction=\"in\" type=\"y\" name=\"keyer\"/>\n"
"      <arg direction=\"in\" type=\"b\" name=\"invert\"/>\n"
"    </method>\n"
"    <method name=\"setUpstreamKeyChromaNarrowRange\">\n"
"      <arg direction=\"in\" type=\"y\" name=\"keyer\"/>\n"
"      <arg direction=\"in\" type=\"b\" name=\"narrowRange\"/>\n"
"    </method>\n"
"    <method name=\"setUpstreamKeyPatternPattern\">\n"
"      <arg direction=\"in\" type=\"y\" name=\"keyer\"/>\n"
"      <arg direction=\"in\" type=\"y\" name=\"pattern\"/>\n"
"    </method>\n"
"    <method name=\"setUpstreamKeyPatternInvertPattern\">\n"
"      <arg direction=\"in\" type=\"y\" name=\"keyer\"/>\n"
"      <arg direction=\"in\" type=\"b\" name=\"invert\"/>\n"
"    </method>\n"
"    <method name=\"setUpstreamKeyDVEDropShadowEnabled\">\n"
"      <arg direction=\"in\" type=\"y\" name=\"keyer\"/>\n"
"      <arg direction=\"in\" type=\"b\" name=\"enabled\"/>\n"
"    </method>\n"
"    <method name=\"setUpstreamKeyDVEBorderEnabled\">\n"
"      <arg direction=\"in\" type=\"y\" name=\"keyer\"/>\n"
"      <arg direction=\"in\" type=\"b\" name=\"enabled\"/>\n"
"    </method>\n"
"    <method name=\"setUpstreamKeyDVEBorderStyle\">\n"
"      <arg direction=\"in\" type=\"y\" name=\"keyer\"/>\n"
"      <arg direction=\"in\" type=\"y\" name=\"style\"/>\n"
"    </method>\n"
"    <method name=\"setUpstreamKeyDVEBorderSoften\">\n"
"      <arg direction=\"in\" type=\"y\" name=\"keyer\"/>\n"
"      <arg direction=\"in\" type=\"y\" name=\"outside\"/>\n"
"      <arg direction=\"in\" type=\"y\" name=\"inside\"/>\n"
"    </method>\n"
"    <method name=\"setUpstreamKeyDVEBorderOpacity\">\n"
"      <arg direction=\"in\" type=\"y\" name=\"keyer\"/>\n"
"      <arg direction=\"in\" type=\"y\" name=\"opacity\"/>\n"
"    </method>\n"
"    <method name=\"setUpstreamKeyDVEBorderBevelSoften\">\n"
"      <arg direction=\"in\" type=\"y\" name=\"keyer\"/>\n"
"      <arg direction=\"in\" type=\"y\" name=\"soften\"/>\n"
"    </method>\n"
"    <method name=\"setUpstreamKeyDVERate\">\n"
"      <arg direction=\"in\" type=\"y\" name=\"keyer\"/>\n"
"      <arg direction=\"in\" type=\"y\" name=\"rate\"/>\n"
"    </method>\n"
"    <method name=\"setUpstreamKeyDVEKeyFrame\">\n"
"      <arg direction=\"in\" type=\"y\" name=\"keyer\"/>\n"
"      <arg direction=\"in\" type=\"y\" name=\"keyFrame\"/>\n"
"    </method>\n"
"    <method name=\"runUpstreamKeyTo\">\n"
"      <arg direction=\"in\" type=\"y\" name=\"keyer\"/>\n"
"      <arg direction=\"in\" type=\"y\" name=\"position\"/>\n"
"      <arg direction=\"in\" type=\"y\" name=\"direction\"/>\n"
"    </method>\n"
"    <method name=\"setUpstreamKeyFlyEnabled\">\n"
"      <arg direction=\"in\" type=\"y\" name=\"keyer\"/>\n"
"      <arg direction=\"in\" type=\"b\" name=\"enable\"/>\n"
"    </method>\n"
"    <method name=\"setDownstreamKeyOn\">\n"
"      <arg direction=\"in\" type=\"y\" name=\"keyer\"/>\n"
"      <arg direction=\"in\" type=\"b\" name=\"state\"/>\n"
"    </method>\n"
"    <method name=\"setDownstreamKeyTie\">\n"
"      <arg direction=\"in\" type=\"y\" name=\"keyer\"/>\n"
"      <arg direction=\"in\" type=\"b\" name=\"state\"/>\n"
"    </method>\n"
"    <method name=\"doDownstreamKeyAuto\">\n"
"      <arg direction=\"in\" type=\"y\" name=\"keyer\"/>\n"
"    </method>\n"
"    <method name=\"setDownstreamKeyFillSource\">\n"
"      <arg direction=\"in\" type=\"y\" name=\"keyer\"/>\n"
"      <arg direction=\"in\" type=\"q\" name=\"source\"/>\n"
"    </method>\n"
"    <method name=\"setDownstreamKeyKeySource\">\n"
"      <arg direction=\"in\" type=\"y\" name=\"keyer\"/>\n"
"      <arg direction=\"in\" type=\"q\" name=\"source\"/>\n"
"    </method>\n"
"    <method name=\"setDownstreamKeyFrameRate\">\n"
"      <arg direction=\"in\" type=\"y\" name=\"keyer\"/>\n"
"      <arg direction=\"in\" type=\"y\" name=\"frames\"/>\n"
"    </method>\n"
"    <method name=\"setDownstreamKeyInvertKey\">\n"
"      <arg direction=\"in\" type=\"y\" name=\"keyer\"/>\n"
"      <arg direction=\"in\" type=\"b\" name=\"invert\"/>\n"
"    </method>\n"
"    <method name=\"setDownstreamKeyPreMultiplied\">\n"
"      <arg direction=\"in\" type=\"y\" name=\"keyer\"/>\n"
"      <arg direction=\"in\" type=\"b\" name=\"preMultiplied\"/>\n"
"    </method>\n"
"    <method name=\"setDownstreamKeyEnableMask\">\n"
"      <arg direction=\"in\" type=\"y\" name=\"keyer\"/>\n"
"      <arg direction=\"in\" type=\"b\" name=\"enable\"/>\n"
"    </method>\n"
"    <method name=\"saveSettings\"/>\n"
"    <method name=\"clearSettings\"/>\n"
"    <method name=\"setMediaPlayerSource\">\n"
"      <arg direction=\"in\" type=\"y\" name=\"player\"/>\n"
"      <arg direction=\"in\" type=\"b\" name=\"clip\"/>\n"
"      <arg direction=\"in\" type=\"y\" name=\"source\"/>\n"
"    </method>\n"
"    <method name=\"setMediaPlayerLoop\">\n"
"      <arg direction=\"in\" type=\"y\" name=\"player\"/>\n"
"      <arg direction=\"in\" type=\"b\" name=\"loop\"/>\n"
"    </method>\n"
"    <method name=\"setMediaPlayerPlay\">\n"
"      <arg direction=\"in\" type=\"y\" name=\"player\"/>\n"
"      <arg direction=\"in\" type=\"b\" name=\"play\"/>\n"
"    </method>\n"
"    <method name=\"mediaPlayerGoToBeginning\">\n"
"      <arg direction=\"in\" type=\"y\" name=\"player\"/>\n"
"    </method>\n"
"    <method name=\"mediaPlayerGoFrameBackward\">\n"
"      <arg direction=\"in\" type=\"y\" name=\"player\"/>\n"
"    </method>\n"
"    <method name=\"mediaPlayerGoFrameForward\">\n"
"      <arg direction=\"in\" type=\"y\" name=\"player\"/>\n"
"    </method>\n"
"    <method name=\"setMixFrames\">\n"
"      <arg direction=\"in\" type=\"y\" name=\"frames\"/>\n"
"    </method>\n"
"    <method name=\"setDipFrames\">\n"
"      <arg direction=\"in\" type=\"y\" name=\"frames\"/>\n"
"    </method>\n"
"    <method name=\"setDipSource\">\n"
"      <arg direction=\"in\" type=\"q\" name=\"source\"/>\n"
"    </method>\n"
"    <method name=\"setWipeBorderSource\">\n"
"      <arg direction=\"in\" type=\"q\" name=\"source\"/>\n"
"    </method>\n"
"    <method name=\"setWipeFrames\">\n"
"      <arg direction=\"in\" type=\"y\" name=\"frames\"/>\n"
"    </method>\n"
"    <method name=\"setWipeBorderWidth\">\n"
"      <arg direction=\"in\" type=\"q\" name=\"width\"/>\n"
"    </method>\n"
"    <method name=\"setWipeBorderSoftness\">\n"
"      <arg direction=\"in\" type=\"q\" name=\"softness\"/>\n"
"    </method>\n"
"    <method name=\"setWipeType\">\n"
"      <arg direction=\"in\" type=\"y\" name=\"type\"/>\n"
"    </method>\n"
"    <method name=\"setWipeSymmetry\">\n"
"      <arg direction=\"in\" type=\"q\" name=\"value\"/>\n"
"    </method>\n"
"    <method name=\"setWipeXPosition\">\n"
"      <arg direction=\"in\" type=\"q\" name=\"value\"/>\n"
"    </method>\n"
"    <method name=\"setWipeYPosition\">\n"
"      <arg direction=\"in\" type=\"q\" name=\"value\"/>\n"
"    </method>\n"
"    <method name=\"setWipeReverseDirection\">\n"
"      <arg direction=\"in\" type=\"b\" name=\"reverse\"/>\n"
"    </method>\n"
"    <method name=\"setWipeFlipFlop\">\n"
"      <arg direction=\"in\" type=\"b\" name=\"flipFlop\"/>\n"
"    </method>\n"
"    <method name=\"setDVERate\">\n"
"      <arg direction=\"in\" type=\"q\" name=\"frames\"/>\n"
"    </method>\n"
"    <method name=\"setDVEEffect\">\n"
"      <arg direction=\"in\" type=\"y\" name=\"effect\"/>\n"
"    </method>\n"
"    <method name=\"setDVEFillSource\">\n"
"      <arg direction=\"in\" type=\"q\" name=\"source\"/>\n"
"    </method>\n"
"    <method name=\"setDVEKeySource\">\n"
"      <arg direction=\"in\" type=\"q\" name=\"source\"/>\n"
"    </method>\n"
"    <method name=\"setDVEKeyEnabled\">\n"
"      <arg direction=\"in\" type=\"b\" name=\"enabled\"/>\n"
"    </method>\n"
"    <method name=\"setDVEPreMultipliedKeyEnabled\">\n"
"      <arg direction=\"in\" type=\"b\" name=\"enabled\"/>\n"
"    </method>\n"
"    <method name=\"setDVEInvertKeyEnabled\">\n"
"      <arg direction=\"in\" type=\"b\" name=\"enabled\"/>\n"
"    </method>\n"
"    <method name=\"setDVEReverseDirection\">\n"
"      <arg direction=\"in\" type=\"b\" name=\"reverse\"/>\n"
"    </method>\n"
"    <method name=\"setDVEFlipFlopDirection\">\n"
"      <arg direction=\"in\" type=\"b\" name=\"flipFlop\"/>\n"
"    </method>\n"
"    <method name=\"setStingerSource\">\n"
"      <arg direction=\"in\" type=\"y\" name=\"source\"/>\n"
"    </method>\n"
"    <method name=\"setStingerPreMultipliedKeyEnabled\">\n"
"      <arg direction=\"in\" type=\"b\" name=\"enabled\"/>\n"
"    </method>\n"
"    <method name=\"setStingerInvertKeyEnabled\">\n"
"      <arg direction=\"in\" type=\"b\" name=\"enabled\"/>\n"
"    </method>\n"
"    <method name=\"setStingerPreRoll\">\n"
"      <arg direction=\"in\" type=\"q\" name=\"frames\"/>\n"
"    </method>\n"
"    <method name=\"setStingerClipDuration\">\n"
"      <arg direction=\"in\" type=\"q\" name=\"frames\"/>\n"
"    </method>\n"
"    <method name=\"setStingerTriggerPoint\">\n"
"      <arg direction=\"in\" type=\"q\" name=\"frames\"/>\n"
"    </method>\n"
"    <method name=\"setStingerMixRate\">\n"
"      <arg direction=\"in\" type=\"q\" name=\"frames\"/>\n"
"    </method>\n"
"    <method name=\"setAuxSource\">\n"
"      <arg direction=\"in\" type=\"y\" name=\"aux\"/>\n"
"      <arg direction=\"in\" type=\"q\" name=\"source\"/>\n"
"    </method>\n"
"    <method name=\"setInputType\">\n"
"      <arg direction=\"in\" type=\"q\" name=\"input\"/>\n"
"      <arg direction=\"in\" type=\"y\" name=\"type\"/>\n"
"    </method>\n"
"    <method name=\"setInputLongName\">\n"
"      <arg direction=\"in\" type=\"q\" name=\"input\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"name\"/>\n"
"    </method>\n"
"    <method name=\"setInputShortName\">\n"
"      <arg direction=\"in\" type=\"q\" name=\"input\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"name\"/>\n"
"    </method>\n"
"    <method name=\"setVideoFormat\">\n"
"      <arg direction=\"in\" type=\"y\" name=\"format\"/>\n"
"    </method>\n"
"    <method name=\"setVideoDownConvertType\">\n"
"      <arg direction=\"in\" type=\"y\" name=\"type\"/>\n"
"    </method>\n"
"    <method name=\"setMediaPoolClipSplit\">\n"
"      <arg direction=\"in\" type=\"y\" name=\"size\"/>\n"
"    </method>\n"
"    <method name=\"setMultiViewLayout\">\n"
"      <arg direction=\"in\" type=\"y\" name=\"layout\"/>\n"
"    </method>\n"
"    <method name=\"setAudioLevelsEnabled\">\n"
"      <arg direction=\"in\" type=\"b\" name=\"enabled\"/>\n"
"    </method>\n"
"    <method name=\"setAudioInputState\">\n"
"      <arg direction=\"in\" type=\"q\" name=\"index\"/>\n"
"      <arg direction=\"in\" type=\"y\" name=\"state\"/>\n"
"    </method>\n"
"    <method name=\"setAudioMonitorEnabled\">\n"
"      <arg direction=\"in\" type=\"b\" name=\"enabled\"/>\n"
"    </method>\n"
"    <method name=\"setAudioMonitorMuted\">\n"
"      <arg direction=\"in\" type=\"b\" name=\"muted\"/>\n"
"    </method>\n"
"    <method name=\"setAudioMonitorDimmed\">\n"
"      <arg direction=\"in\" type=\"b\" name=\"dimmed\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    QAtemConnectionAdaptor(QObject *parent);
    virtual ~QAtemConnectionAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    bool aquireMediaLock(uchar id, uchar index);
    bool audioMonitorDimmed();
    bool audioMonitorEnabled();
    bool audioMonitorMuted();
    bool audioTallyState(ushort index);
    ushort auxSource(uchar aux);
    void changePreviewInput(ushort index);
    void changeProgramInput(ushort index);
    void clearSettings();
    void connectToSwitcher(const QString &name);
    uchar currentTransitionStyle();
    bool debugEnabled();
    uchar dipFrames();
    ushort dipSource();
    void disconnectFromSwitcher();
    void doAuto();
    void doCut();
    void doDownstreamKeyAuto(uchar keyer);
    short downstreamKeyBottomMask(uchar keyer);
    ushort downstreamKeyClip(uchar keyer);
    bool downstreamKeyEnableMask(uchar keyer);
    ushort downstreamKeyFillSource(uchar keyer);
    uchar downstreamKeyFrameCount(uchar keyer);
    uchar downstreamKeyFrames(uchar keyer);
    ushort downstreamKeyGain(uchar keyer);
    bool downstreamKeyInvertKey(uchar keyer);
    ushort downstreamKeyKeySource(uchar keyer);
    short downstreamKeyLeftMask(uchar keyer);
    bool downstreamKeyOn(uchar keyer);
    bool downstreamKeyPreMultiplied(uchar keyer);
    short downstreamKeyRightMask(uchar keyer);
    bool downstreamKeyTie(uchar keyer);
    short downstreamKeyTopMask(uchar keyer);
    uchar dveEffect();
    ushort dveFillSource();
    bool dveFlipFlopDirection();
    bool dveInvertKeyEnabled();
    bool dveKeyEnabled();
    ushort dveKeySource();
    bool dvePreMultipliedKeyEnabled();
    ushort dveRate();
    bool dveReverseDirection();
    bool fadeToBlackEnabled();
    bool fadeToBlackFading();
    uchar fadeToBlackFrameCount();
    uchar fadeToBlackFrames();
    uchar framesPerSecond();
    uchar keyersOnCurrentTransition();
    uchar keyersOnNextTransition();
    ushort majorVersion();
    bool mediaLockState(uchar id);
    void mediaPlayerGoFrameBackward(uchar player);
    void mediaPlayerGoFrameForward(uchar player);
    void mediaPlayerGoToBeginning(uchar player);
    uchar mediaPlayerSelectedClip(uchar player);
    uchar mediaPlayerSelectedStill(uchar player);
    uchar mediaPlayerType(uchar player);
    uchar mediaPoolClip1Size();
    uchar mediaPoolClip2Size();
    ushort minorVersion();
    uchar mixFrames();
    uchar multiViewInput(uchar multiViewOutput);
    uchar multiViewLayout();
    uchar nextTransitionStyle();
    ushort previewInput();
    QString productInformation();
    ushort programInput();
    int remainingTransferDataSize();
    void runUpstreamKeyTo(uchar keyer, uchar position, uchar direction);
    void saveSettings();
    ushort sendDataToSwitcher(uchar storeId, uchar index, const QByteArray &name, const QByteArray &data);
    void setAudioInputState(ushort index, uchar state);
    void setAudioLevelsEnabled(bool enabled);
    void setAudioMonitorDimmed(bool dimmed);
    void setAudioMonitorEnabled(bool enabled);
    void setAudioMonitorMuted(bool muted);
    void setAuxSource(uchar aux, ushort source);
    void setBackgroundOnNextTransition(bool state);
    void setDVEEffect(uchar effect);
    void setDVEFillSource(ushort source);
    void setDVEFlipFlopDirection(bool flipFlop);
    void setDVEInvertKeyEnabled(bool enabled);
    void setDVEKeyEnabled(bool enabled);
    void setDVEKeySource(ushort source);
    void setDVEPreMultipliedKeyEnabled(bool enabled);
    void setDVERate(ushort frames);
    void setDVEReverseDirection(bool reverse);
    void setDebugEnabled(bool enabled);
    void setDipFrames(uchar frames);
    void setDipSource(ushort source);
    void setDownstreamKeyEnableMask(uchar keyer, bool enable);
    void setDownstreamKeyFillSource(uchar keyer, ushort source);
    void setDownstreamKeyFrameRate(uchar keyer, uchar frames);
    void setDownstreamKeyInvertKey(uchar keyer, bool invert);
    void setDownstreamKeyKeySource(uchar keyer, ushort source);
    void setDownstreamKeyOn(uchar keyer, bool state);
    void setDownstreamKeyPreMultiplied(uchar keyer, bool preMultiplied);
    void setDownstreamKeyTie(uchar keyer, bool state);
    void setFadeToBlackFrameRate(uchar frames);
    void setInputLongName(ushort input, const QString &name);
    void setInputShortName(ushort input, const QString &name);
    void setInputType(ushort input, uchar type);
    void setMediaPlayerLoop(uchar player, bool loop);
    void setMediaPlayerPlay(uchar player, bool play);
    void setMediaPlayerSource(uchar player, bool clip, uchar source);
    void setMediaPoolClipSplit(uchar size);
    void setMixFrames(uchar frames);
    void setMultiViewLayout(uchar layout);
    void setStingerClipDuration(ushort frames);
    void setStingerInvertKeyEnabled(bool enabled);
    void setStingerMixRate(ushort frames);
    void setStingerPreMultipliedKeyEnabled(bool enabled);
    void setStingerPreRoll(ushort frames);
    void setStingerSource(uchar source);
    void setStingerTriggerPoint(ushort frames);
    void setTransitionPosition(ushort position);
    void setTransitionPreview(bool state);
    void setTransitionType(uchar type);
    void setUpstreamKeyChromaNarrowRange(uchar keyer, bool narrowRange);
    void setUpstreamKeyDVEBorderBevelSoften(uchar keyer, uchar soften);
    void setUpstreamKeyDVEBorderEnabled(uchar keyer, bool enabled);
    void setUpstreamKeyDVEBorderOpacity(uchar keyer, uchar opacity);
    void setUpstreamKeyDVEBorderSoften(uchar keyer, uchar outside, uchar inside);
    void setUpstreamKeyDVEBorderStyle(uchar keyer, uchar style);
    void setUpstreamKeyDVEDropShadowEnabled(uchar keyer, bool enabled);
    void setUpstreamKeyDVEKeyFrame(uchar keyer, uchar keyFrame);
    void setUpstreamKeyDVERate(uchar keyer, uchar rate);
    void setUpstreamKeyEnableMask(uchar keyer, bool enable);
    void setUpstreamKeyFillSource(uchar keyer, ushort source);
    void setUpstreamKeyFlyEnabled(uchar keyer, bool enable);
    void setUpstreamKeyKeySource(uchar keyer, ushort source);
    void setUpstreamKeyLumaInvertKey(uchar keyer, bool invert);
    void setUpstreamKeyLumaPreMultipliedKey(uchar keyer, bool preMultiplied);
    void setUpstreamKeyOn(uchar keyer, bool state);
    void setUpstreamKeyOnNextTransition(uchar keyer, bool state);
    void setUpstreamKeyPatternInvertPattern(uchar keyer, bool invert);
    void setUpstreamKeyPatternPattern(uchar keyer, uchar pattern);
    void setUpstreamKeyType(uchar keyer, uchar type);
    void setVideoDownConvertType(uchar type);
    void setVideoFormat(uchar format);
    void setWipeBorderSoftness(ushort softness);
    void setWipeBorderSource(ushort source);
    void setWipeBorderWidth(ushort width);
    void setWipeFlipFlop(bool flipFlop);
    void setWipeFrames(uchar frames);
    void setWipeReverseDirection(bool reverse);
    void setWipeSymmetry(ushort value);
    void setWipeType(uchar type);
    void setWipeXPosition(ushort value);
    void setWipeYPosition(ushort value);
    void signalTransitionPositionChangeDone();
    ushort stingerClipDuration();
    bool stingerInvertKeyEnabled();
    ushort stingerMixRate();
    bool stingerPreMultipliedKeyEnabled();
    ushort stingerPreRoll();
    uchar stingerSource();
    ushort stingerTriggerPoint();
    uchar tallyState(uchar id);
    uchar tallyStateCount();
    void toggleFadeToBlack();
    bool transferActive();
    ushort transferId();
    uchar transitionFrameCount();
    ushort transitionPosition();
    bool transitionPreviewEnabled();
    void unlockMediaLock(uchar id);
    bool upstreamKeyChromaNarrowRange(uchar keyer);
    uchar upstreamKeyDVEBorderBevelSofter(uchar keyer);
    bool upstreamKeyDVEBorderEnabled(uchar keyer);
    uchar upstreamKeyDVEBorderInsideSoften(uchar keyer);
    uchar upstreamKeyDVEBorderOpacity(uchar keyer);
    uchar upstreamKeyDVEBorderOutsideSoften(uchar keyer);
    uchar upstreamKeyDVEBorderStyle(uchar keyer);
    bool upstreamKeyDVEDropShadowEnabled(uchar keyer);
    bool upstreamKeyDVEKeyFrameASet(uchar keyer);
    bool upstreamKeyDVEKeyFrameBSet(uchar keyer);
    uchar upstreamKeyDVELightSourceAltitude(uchar keyer);
    uchar upstreamKeyDVERate(uchar keyer);
    bool upstreamKeyEnableFly(uchar keyer);
    bool upstreamKeyEnableMask(uchar keyer);
    ushort upstreamKeyFillSource(uchar keyer);
    ushort upstreamKeyKeySource(uchar keyer);
    bool upstreamKeyLumaInvertKey(uchar keyer);
    bool upstreamKeyLumaPreMultipliedKey(uchar keyer);
    bool upstreamKeyOn(uchar keyer);
    bool upstreamKeyPatternInvertPattern(uchar keyer);
    uchar upstreamKeyPatternPattern(uchar keyer);
    uchar upstreamKeyType(uchar keyer);
    uchar videoDownConvertType();
    uchar videoFormat();
    ushort wipeBorderSoftness();
    ushort wipeBorderSource();
    ushort wipeBorderWidth();
    bool wipeFlipFlop();
    uchar wipeFrames();
    bool wipeReverseDirection();
    ushort wipeSymmetry();
    uchar wipeType();
    ushort wipeXPosition();
    ushort wipeYPosition();
Q_SIGNALS: // SIGNALS
    void audioLevelsChanged();
    void audioMonitorDimmedChanged(bool dimmed);
    void audioMonitorEnabledChanged(bool enabled);
    void audioMonitorMutedChanged(bool muted);
    void auxSourceChanged(uchar aux, ushort source);
    void connected();
    void currentTransitionStyleChanged(uchar style);
    void dataTransferFinished(ushort transferId);
    void dipFramesChanged(uchar frames);
    void dipSourceChanged(ushort source);
    void disconnected();
    void downstreamKeyEnableMaskChanged(uchar keyer, bool enable);
    void downstreamKeyFrameCountChanged(uchar keyer, uchar count);
    void downstreamKeyFramesChanged(uchar keyer, uchar frames);
    void downstreamKeyInvertKeyChanged(uchar keyer, bool invert);
    void downstreamKeyOnChanged(uchar keyer, bool state);
    void downstreamKeyPreMultipliedChanged(uchar keyer, bool preMultiplied);
    void downstreamKeySourcesChanged(uchar keyer, ushort fill, ushort key);
    void downstreamKeyTieChanged(uchar keyer, bool state);
    void dveEffectChanged(uchar effect);
    void dveEnableInvertKeyChanged(bool enabled);
    void dveEnableKeyChanged(bool enabled);
    void dveEnablePreMultipliedKeyChanged(bool enabled);
    void dveFillSourceChanged(ushort source);
    void dveFlipFlopDirectionChanged(bool flipFlop);
    void dveKeySourceChanged(ushort source);
    void dveRateChanged(ushort frames);
    void dveReverseDirectionChanged(bool reverse);
    void fadeToBlackChanged(bool fading, bool enabled);
    void fadeToBlackFrameCountChanged(uchar count);
    void fadeToBlackFramesChanged(uchar frames);
    void keyersOnCurrentTransitionChanged(uchar keyers);
    void keyersOnNextTransitionChanged(uchar keyers);
    void mediaLockStateChanged(uchar id, bool state);
    void mediaPlayerChanged(uchar player, uchar type, uchar still, uchar clip);
    void mediaPoolClip1SizeChanged(uchar size);
    void mediaPoolClip2SizeChanged(uchar size);
    void mixFramesChanged(uchar frames);
    void nextTransitionStyleChanged(uchar style);
    void previewInputChanged(ushort oldIndex, ushort newIndex);
    void productInformationChanged(const QString &info);
    void programInputChanged(ushort oldIndex, ushort newIndex);
    void socketError(const QString &errorString);
    void stingerClipDurationChanged(ushort frames);
    void stingerEnableInvertKeyChanged(bool enabled);
    void stingerEnablePreMultipliedKeyChanged(bool enabled);
    void stingerMixRateChanged(ushort frames);
    void stingerPreRollChanged(ushort frames);
    void stingerSourceChanged(uchar source);
    void stingerTriggerPointChanged(ushort frames);
    void tallyStatesChanged();
    void timeChanged(uint time);
    void transitionFrameCountChanged(uchar count);
    void transitionPositionChanged(ushort count);
    void transitionPreviewChanged(bool state);
    void upstreamKeyChromaNarrowRangeChanged(uchar keyer, bool narrowRange);
    void upstreamKeyDVEBorderInsideSoftenChanged(uchar keyer, uchar soften);
    void upstreamKeyDVEBorderOpacityChanged(uchar keyer, uchar opacity);
    void upstreamKeyDVEBorderOutsideSoftenChanged(uchar keyer, uchar soften);
    void upstreamKeyDVEBorderStyleChanged(uchar keyer, uchar style);
    void upstreamKeyDVEEnableBorderChanged(uchar keyer, bool enable);
    void upstreamKeyDVEEnableDropShadowChanged(uchar keyer, bool enable);
    void upstreamKeyDVEKeyFrameASetChanged(uchar keyer, bool set);
    void upstreamKeyDVEKeyFrameBSetChanged(uchar keyer, bool set);
    void upstreamKeyDVELightSourceAltitudeChanged(uchar keyer, uchar altitude);
    void upstreamKeyDVERateChanged(uchar keyer, uchar rate);
    void upstreamKeyEnableFlyChanged(uchar keyer, bool enabled);
    void upstreamKeyEnableMaskChanged(uchar keyer, bool enable);
    void upstreamKeyFillSourceChanged(uchar keyer, ushort source);
    void upstreamKeyKeySourceChanged(uchar keyer, ushort source);
    void upstreamKeyLumaInvertKeyChanged(uchar keyer, bool invert);
    void upstreamKeyLumaPreMultipliedKeyChanged(uchar keyer, bool preMultiplied);
    void upstreamKeyOnChanged(uchar keyer, bool state);
    void upstreamKeyPatternInvertPatternChanged(uchar keyer, bool invert);
    void upstreamKeyPatternPatternChanged(uchar keyer, uchar pattern);
    void upstreamKeyTypeChanged(uchar keyer, uchar type);
    void versionChanged(ushort major, ushort minor);
    void videoDownConvertTypeChanged(uchar type);
    void videoFormatChanged(uchar format);
    void wipeBorderSoftnessChanged(ushort softness);
    void wipeBorderSourceChanged(ushort index);
    void wipeBorderWidthChanged(ushort width);
    void wipeFlipFlopChanged(bool flipFlop);
    void wipeFramesChanged(uchar frames);
    void wipeReverseDirectionChanged(bool reverse);
    void wipeSymmetryChanged(ushort value);
    void wipeTypeChanged(uchar type);
    void wipeXPositionChanged(ushort value);
    void wipeYPositionChanged(ushort value);
};

#endif
